receivers:
 otlp:
   protocols:
     http:
       cors:
         allowed_origins:
         - https://3000*.com
         - https://3000*.com

processors:
 batch:

exporters:
 otlp/honeycomb:
   endpoint: "api.honeycomb.io:443"
   headers:
     "x-honeycomb-team": "bNOlJUSUx5uqOaIxOOsDFB"
     "x-honeycomb-dataset": "frontend-react-js"

service:
 pipelines:
   traces:
     receivers: [otlp]
     processors: [batch]
     exporters: [otlp/honeycomb]